---
version: "2"

services:

  hub:
    build: .
    image: websub-base
    extra_hosts:
      - hub.websub.local:172.31.1.2
      - pub.websub.local:172.31.1.3
      - sub.websub.local:172.31.1.4
    hostname: hub
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    networks:
      websub:
        ipv4_address: 172.31.1.2
        aliases:
          - hub.websub.local

  pub:
    build: .
    image: websub-base
    extra_hosts:
      - hub.websub.local:172.31.1.2
      - pub.websub.local:172.31.1.3
      - sub.websub.local:172.31.1.4
    hostname: pub
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    networks:
      websub:
        ipv4_address: 172.31.1.3
        aliases:
          - pub.websub.local

  sub:
    build: .
    image: websub-base
    extra_hosts:
      - hub.websub.local:172.31.1.2
      - pub.websub.local:172.31.1.3
      - sub.websub.local:172.31.1.4
    hostname: sub
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    networks:
      websub:
        ipv4_address: 172.31.1.4
        aliases:
          - sub.websub.local

networks:
  websub:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.1.0/24
          gateway: 172.31.1.1
