---
version: "2"

services:

  hub:
    build: .
    image: websub:hub
    extra_hosts:
      - hub.websub.local:172.31.1.2
      - mdq.websub.local:172.31.1.3
      - feda.websub.local:172.31.1.4
      - fedb.websub.local:172.31.1.5
    hostname: hub
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./websub:/opt/websub"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    networks:
      websub:
        ipv4_address: 172.31.1.2
        aliases:
          - hub.websub.local

  mdq:
    build: .
    image: websub:mdq
    extra_hosts:
      - hub.websub.local:172.31.1.2
      - mdq.websub.local:172.31.1.3
      - feda.websub.local:172.31.1.4
      - fedb.websub.local:172.31.1.5
    hostname: mdq
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./pyFF:/opt/pyFF"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    networks:
      websub:
        ipv4_address: 172.31.1.3
        aliases:
          - mdq.websub.local

  feda:
    #build: nginx:stable
    image: nginx:stable
    extra_hosts:
      - hub.websub.local:172.31.1.2
      - pub.websub.local:172.31.1.3
      - feda.websub.local:172.31.1.4
      - fedb.websub.local:172.31.1.5
    hostname: feda
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/nginx/html:/usr/share/nginx/html"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    networks:
      websub:
        ipv4_address: 172.31.1.4
        aliases:
          - feda.websub.local

  fedb:
    build: .
    image: websub:fedb
    extra_hosts:
      - hub.websub.local:172.31.1.2
      - pub.websub.local:172.31.1.3
      - feda.websub.local:172.31.1.4
      - fedb.websub.local:172.31.1.5
    hostname: fedb
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./pyFF:/opt/pyFF"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    networks:
      websub:
        ipv4_address: 172.31.1.5
        aliases:
          - fedb.websub.local

networks:
  websub:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.1.0/24
          gateway: 172.31.1.1
